# Generated by Django 3.1 on 2020-08-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
