# Generated by Django 3.1 on 2020-08-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='description',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
