# Generated by Django 3.1 on 2020-08-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_paragraph_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
