# Generated by Django 3.1 on 2020-08-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20200823_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
