# Generated by Django 3.1 on 2020-09-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
